version: "3"

services: 
    node: 
        restart: always
        build: .
        ports: 
            - 8080:5000
        links: 
            - mongo
        volumes: 
            - .:/app
    mongo:
        image: mongo
        ports: 
            - 27018:27017
        